import { userPortfolio } from "@/server/units/units";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Metadata } from "next";
import Link from "next/link";
import { ShowPortfolio } from "./(partials)/ShowPortfolio";
import Search from "@/components/ui/search";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default async function Portfolio(props: {
  searchParams?: Promise<{
    query?: string;
    page?: string;
  }>;
}) {
  const searchParams = await props.searchParams;
  const query = searchParams?.query || "";

  const portfolio = await userPortfolio(query);

  return (
    <>
      <div className="flex">
        <div className="md:w-8/12">
          <Card>
            <CardContent className="md:p-10 p-5">
              <div className="flex items-center w-full mb-5 space-x-2">
                <Search type="email" placeholder="Search for your properties" />
              </div>

              <div className="divide-y-2">
                {portfolio.length > 0 ? (
                  <ShowPortfolio portfolio={portfolio} />
                ) : query ? (
                  <h1 className="md:text-xl font-semibold">
                    No property match your search
                  </h1>
                ) : (
                  <div className="md:p-10 p-5 space-y-5 text-center">
                    <h1 className="md:text-xl font-semibold">
                      You have not purchased any property slots yet!
                    </h1>
                    <Button asChild>
                      <Link href={"/properties"}>Find Properties</Link>
                    </Button>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  );
}
