import { listProperties } from '@/server/property/list'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import React from 'react'
import { ShowProperties } from './(partials)/ShowProperties'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Invest',
	description: 'Generated by create next app',
}

export default async function Invest() {
    const properties = await listProperties()
    
    return (
        <>
            <div className="flex">
                <div className="md:w-8/12 w-full">
                    <Card>
                        <CardContent className='py-10 space-y-5' >
                            <div className="flex items-center w-full space-x-2">
                                <Input type="email" placeholder="Search for available properties" />
                            </div>

                            <ShowProperties properties={properties} />
                        </CardContent>
                    </Card>
                </div>
            </div>
        </>
    )
}
