import { listProperties } from "@/server/property/list";
import { Card, CardContent } from "@/components/ui/card";
import Search from "@/components/ui/search";
import React, { Suspense } from "react";
import { ShowProperties } from "./(partials)/ShowProperties";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Invest",
  description: "Generated by create next app",
};

export default async function Invest(props: {
  searchParams?: Promise<{
    query?: string;
    page?: string;
  }>;
}) {
  const searchParams = await props.searchParams;
  const query = searchParams?.query || "";

  const properties = await listProperties(query);
  return (
    <>
      <div className="flex">
        <div className="md:w-8/12 w-full">
          <Card>
            <CardContent className="py-10 space-y-5">
              <div className="flex items-center w-full space-x-2">
                <Search placeholder="Search for property" />
              </div>
              <ShowProperties properties={properties} />
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  );
}
